#!/usr/bin/env zsh

# Use $XINITRC variable if file exists.
[ -f "$XINITRC" ] && alias startx="startx $XINITRC"

# Colorize commands when possible.
LS_COLORS='di=1;35:fi=0:ln=31:pi=5:so=5:bd=5:cd=5:or=31:mi=0:ex=35:*.rpm=90:*.png=35:*.gif=36:*.jpg=35:*.c=92:*.jar=33:*.py=93:*.h=90:*.txt=94:*.doc=104:*.docx=104:*.odt=104:*.csv=102:*.xlsx=102:*.xlsm=102:*.rb=31:*.cpp=92:*.sh=92:*.html=96:*.zip=4;33:*.tar.gz=4;33:*.mp4=105:*.mp3=106'
export LS_COLORS
alias ls="exa --oneline --group-directories-first"
alias l="exa --long --all --group-directories-first"
alias	grep="grep --color=auto"
alias	diff="diff --color=auto"
alias	cat="bat"
alias e="emacsclient -n -c"

# Nix
alias npmig='npm install -g --unsafe-perm'
alias nixRF="nixos-rebuild switch --flake '/etc/nixos#`uname -n`'"
alias homeRF="home-manager switch --flake '/root/.config/nixpkgs#nixos-desktop'"
